---
- name: create symlinks
  file: >
    state=link
    src="{{ item.src }}"
    dest="{{ rails_app_base_path }}/{{ item.dir }}"
    force=yes
  with_items: rails_app_sub_dirs
  when: item.src is defined
