# Required VARS:
#   - rails_app_host
#   - rails_app_port
#
---
- name: check if application is up
  uri: >
    url="http://{{ rails_app_host }}:{{ rails_app_port }}"
  register: application_response
  until: application_response.status == 200
  delay: 10
  retries: 15
