---
- name: check if passenger is running
  stat: >
    path="{{ rails_app_pids_path }}/{{ item.id }}.pid"
  with_items: rails_app_all_instances
  register: passenger_instances

- name: stop passenger processes (w/ rvm)
  command: "bash -lc 'bundle exec passenger stop -p {{ item.item.port }} --pid-file {{ rails_app_pids_path }}/{{ item.item.id }}.pid'"
  args:
    chdir: "{{ rails_app_current_path }}"
  with_items: passenger_instances.results
  when: item.stat is defined and item.stat.exists

- name: wait for passenger instances to stop...
  wait_for: >
    state=absent
    path="{{ rails_app_pids_path }}/{{ item.item.id }}.pid"
    delay=5
    timeout=720
  with_items: passenger_instances.results
  when: item.stat is defined and item.stat.exists
