---
- name: check if passenger is running
  stat: >
    path="{{ rails_app_pids_path }}/{{ rails_app_id }}.pid"
  register: passenger_instances

- name: stop passenger processes (w/ rvm)
  command: "bash -lc 'bundle exec passenger stop -p {{ rails_app_port }} --pid-file {{ rails_app_pids_path }}/{{ rails_app_id }}.pid'"
  args:
    chdir: "{{ rails_app_current_path }}"
  when: passenger_instances.stat is defined and passenger_instances.stat.exists

- name: wait for passenger instances to stop...
  wait_for: >
    state=absent
    path="{{ rails_app_pids_path }}/{{ rails_app_id }}.pid"
    delay=5
    timeout=720
