---
- name: rake db:create
  shell: bash -lc 'bundle exec rake db:create'
  args:
    chdir: "{{ rails_app_path }}"
  register: rake_db_create
  run_once: true
  environment: rails_app_environment
  when: rails_app_strategy == 'setup'

- name: check schema.rb
  stat: >
    path="{{ rails_app_path }}/db/schema.rb"
  register: schema
  run_once: true
  environment: rails_app_environment
  when: rails_app_strategy == 'setup'

- name: load database schema
  shell: bash -lc 'bundle exec rake db:schema:load'
  args:
    chdir: "{{ rails_app_path }}"
  run_once: true
  when: rails_app_strategy == 'setup' and schema is defined and schema.stat.exists
  environment: rails_app_environment

- name: check for migrations
  stat: >
    path="{{ rails_app_path }}/db/migrate"
  register: migrations
  run_once: true
  when: rails_app_strategy == 'deploy'
  environment: rails_app_environment

- name: run database migrations
  shell: bash -lc 'bundle exec rake db:migrate'
  args:
    chdir: "{{ rails_app_path }}"
  run_once: true
  environment: rails_app_environment
  when: rails_app_strategy == 'deploy'
